#!/usr/bin/env python3
"""Generate supabase/migrations/20260719000003_wp_seed_from_xlsx.sql from the
Luxium capacity model. Run once at build time; the emitted SQL is committed and
is what actually applies to a database. Idempotent: re-running the SQL is safe.

Usage: python3 scripts/wp_seed_from_xlsx.py ~/Downloads/luxium_capacity_model.xlsx
"""
import sys, openpyxl

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    __import__('os').path.expanduser('~/Downloads/luxium_capacity_model.xlsx')
OUT = 'supabase/migrations/20260719000003_wp_seed_from_xlsx.sql'

def q(v):
    if v is None: return 'null'
    return "'" + str(v).replace("'", "''").strip() + "'"

def num(v):
    if v in (None, ''): return 'null'
    try: return repr(float(v))
    except (TypeError, ValueError): return 'null'

wb = openpyxl.load_workbook(SRC, data_only=True)

# --- Nodes: Lists sheet, "Value chain node" column A, rows 4.. until blank ---
nodes = []  # (code, name)
ws = wb['Lists']
for r in range(4, ws.max_row + 1):
    name = ws.cell(r, 1).value
    if not name or not str(name).strip(): continue
    name = str(name).strip()
    code = name.split('.', 1)[0].strip() if '.' in name else name.split()[0].strip()
    nodes.append((code, name))

# --- Drivers (Block 1) + Rates (Block 2) from Drivers sheet ---
ws = wb['Drivers']
drivers, rates = [], []  # drivers: (name,value,grows); rates: (name,minutes)
mode = None
for r in range(1, ws.max_row + 1):
    a = ws.cell(r, 1).value
    at = str(a).strip() if a else ''
    if at.startswith('BLOCK 1'): mode = 'drv'; continue
    if at.startswith('BLOCK 2'): mode = 'rate'; continue
    if not at or at.lower() == 'driver' or at.lower() == 'rate': continue
    if mode == 'drv':
        val = ws.cell(r, 2).value
        grows = str(ws.cell(r, 4).value or '').strip().upper().startswith('Y')
        if val is not None and str(val).strip() != '':
            drivers.append((at, val, grows))
    elif mode == 'rate':
        mins = ws.cell(r, 2).value
        if mins is not None and str(mins).strip() != '':
            rates.append((at, mins))

# value -> unique driver name (for best-effort volume binding)
from collections import Counter
val_counts = Counter(round(float(v), 6) for _, v, _ in drivers if str(v).strip() != '')
val_to_driver = {round(float(v), 6): n for n, v, _ in drivers
                 if val_counts[round(float(v), 6)] == 1}

# --- Tasks sheet ---
ws = wb['Tasks']
tasks = []
for r in range(5, ws.max_row + 1):
    tid = ws.cell(r, 1).value
    name = ws.cell(r, 3).value
    if not tid or not name: continue
    cadence = str(ws.cell(r, 5).value or '').strip()
    times = ws.cell(r, 6).value
    minutes = ws.cell(r, 7).value
    is_volume = 'volume' in cadence.lower() or 'per-unit' in cadence.lower()
    bind = None
    if is_volume and times is not None:
        bind = val_to_driver.get(round(float(times), 6))
    tasks.append(dict(
        ref=str(tid).strip(),
        node=str(ws.cell(r, 2).value or '').strip(),
        name=str(name).strip(),
        brand=ws.cell(r, 4).value,
        cadence=cadence or None,
        times=times, minutes=minutes, bind_driver=bind,
        tier=ws.cell(r, 9).value, risk=ws.cell(r, 10).value,
        capability=ws.cell(r, 11).value, owner=ws.cell(r, 12).value,
    ))

# --- Emit SQL ---
L = []
L.append("-- GENERATED by scripts/wp_seed_from_xlsx.py from luxium_capacity_model.xlsx.")
L.append("-- One-time Luxium capacity-model seed. Idempotent. Do not hand-edit; regenerate.")
L.append("do $$")
L.append("declare v_company uuid;")
L.append("begin")
L.append("  if (select count(*) from companies) <> 1 then")
L.append("    raise exception 'wp seed: expected exactly one company; set v_company explicitly';")
L.append("  end if;")
L.append("  select id into v_company from companies limit 1;")
for i, (code, name) in enumerate(nodes):
    L.append(f"  insert into wp_value_chain_nodes(company_id, code, name, sort_order) "
             f"select v_company, {q(code)}, {q(name)}, {i} "
             f"where not exists (select 1 from wp_value_chain_nodes n "
             f"where n.company_id=v_company and lower(trim(n.name))=lower(trim({q(name)})));")
for n, v, g in drivers:
    L.append(f"  insert into wp_drivers(company_id, name, value, grows) "
             f"select v_company, {q(n)}, {num(v)}, {str(g).lower()} "
             f"where not exists (select 1 from wp_drivers d "
             f"where d.company_id=v_company and lower(trim(d.name))=lower(trim({q(n)})));")
for n, m in rates:
    L.append(f"  insert into wp_rates(company_id, name, minutes_each) "
             f"select v_company, {q(n)}, {num(m)} "
             f"where not exists (select 1 from wp_rates r "
             f"where r.company_id=v_company and lower(trim(r.name))=lower(trim({q(n)})));")
for t in tasks:
    owner = (f"(select id from employees where company_id=v_company and "
             f"lower(trim(first_name||' '||last_name))=lower(trim({q(t['owner'])})) limit 1)") \
             if t['owner'] and str(t['owner']).strip() and str(t['owner']).strip().upper() != 'UNASSIGNED' \
             else "null"
    node = (f"(select id from wp_value_chain_nodes where company_id=v_company and "
            f"lower(trim(name))=lower(trim({q(t['node'])})) limit 1)") if t['node'] else "null"
    if t['bind_driver']:
        tsrc, tman = "'driver'", "null"
        drv = (f"(select id from wp_drivers where company_id=v_company and "
               f"lower(trim(name))=lower(trim({q(t['bind_driver'])})) limit 1)")
    else:
        tsrc, tman, drv = "'manual'", num(t['times']), "null"
    tier = q(t['tier']) if t['tier'] in ('Transactional','Operational','Managerial','Strategic') else 'null'
    risk = q(t['risk']) if t['risk'] in ('Low','Medium','High') else 'null'
    L.append(
        "  insert into wp_tasks(company_id, external_ref, name, node_id, brand_scope, cadence, "
        "times_source, times_manual, driver_id, minutes_source, minutes_manual, skill_tier, risk, "
        "capability, owner_employee_id) values ("
        f"v_company, {q(t['ref'])}, {q(t['name'])}, {node}, {q(t['brand'])}, {q(t['cadence'])}, "
        f"{tsrc}, {tman}, {drv}, 'manual', {num(t['minutes'])}, {tier}, {risk}, "
        f"{q(t['capability'])}, {owner}) "
        "on conflict (company_id, external_ref) where external_ref is not null do update set "
        "name=excluded.name, node_id=excluded.node_id, brand_scope=excluded.brand_scope, "
        "cadence=excluded.cadence, times_source=excluded.times_source, times_manual=excluded.times_manual, "
        "driver_id=excluded.driver_id, minutes_source=excluded.minutes_source, "
        "minutes_manual=excluded.minutes_manual, skill_tier=excluded.skill_tier, risk=excluded.risk, "
        "capability=excluded.capability, owner_employee_id=excluded.owner_employee_id, updated_at=now();")
L.append("  insert into wp_config(company_id) select v_company "
         "where not exists (select 1 from wp_config where company_id=v_company);")
L.append("end $$;")
open(OUT, 'w').write("\n".join(L) + "\n")
print(f"Wrote {OUT}: {len(nodes)} nodes, {len(drivers)} drivers, {len(rates)} rates, {len(tasks)} tasks")
